/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // ── Stitch SvaraMap exact color palette ──────────────
        'on-error':                    '#690005',
        'surface-container-lowest':    '#120d07',
        'primary-fixed-dim':           '#ffb4a9',
        'primary-container':           '#ff8574',
        'on-primary-container':        '#800504',
        'surface-variant':             '#3b342c',
        'surface-container-high':      '#2f2922',
        'primary':                     '#ffb4a9',
        'inverse-surface':             '#ede0d5',
        'secondary-container':         '#c59300',
        'surface-container-highest':   '#3b342c',
        'surface':                     '#18120c',
        'surface-container-low':       '#201b14',
        'on-secondary-fixed-variant':  '#5c4300',
        'on-surface':                  '#ede0d5',
        'on-secondary-container':      '#433000',
        'primary-fixed':               '#ffdad5',
        'error':                       '#ffb4ab',
        'inverse-on-surface':          '#362f28',
        'on-primary':                  '#690001',
        'on-secondary':                '#402d00',
        'background':                  '#18120c',
        'on-error-container':          '#ffdad6',
        'tertiary-container':          '#94a5e8',
        'on-primary-fixed':            '#410000',
        'surface-dim':                 '#18120c',
        'on-tertiary':                 '#192c68',
        'surface-tint':                '#ffb4a9',
        'on-tertiary-container':       '#273975',
        'tertiary-fixed-dim':          '#b6c4ff',
        'secondary':                   '#f6be39',
        'outline-variant':             '#4f4634',
        'on-secondary-fixed':          '#261a00',
        'tertiary-fixed':              '#dce1ff',
        'on-tertiary-fixed-variant':   '#31437f',
        'on-background':               '#ede0d5',
        'tertiary':                    '#b6c4ff',
        'secondary-fixed-dim':         '#f6be39',
        'on-primary-fixed-variant':    '#8e130c',
        'secondary-fixed':             '#ffdfa0',
        'on-surface-variant':          '#d3c5ae',
        'surface-bright':              '#3f3830',
        'surface-container':           '#251f18',
        'error-container':             '#93000a',
        'outline':                     '#9b8f7a',
        'inverse-primary':             '#b02d21',
        'on-tertiary-fixed':           '#00164f',
        // ── Named semantic aliases ──────────────────────────
        'gold':       '#D4A017',
        'vermillion': '#C0392B',
        'indigo-ink': '#2C3E7A',
        'ivory':      '#ede0d5',
        'soot':       '#0F0A05',
      },
      fontFamily: {
        'headline':  ['Newsreader', 'serif'],
        'body':      ['"Noto Serif Devanagari"', 'serif'],
        'label':     ['"Courier Prime"', 'monospace'],
        'yatra':     ['"Yatra One"', 'cursive'],
        'grotesk':   ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      transitionDuration: {
        '500': '500ms',
        '600': '600ms',
        '800': '800ms',
      },
      animation: {
        'spin-slow':   'spin 9s linear infinite',
        'fade-up':     'fadeUp 0.8s ease forwards',
        'path-draw':   'pathDraw 2.4s cubic-bezier(0.23,1,0.32,1) forwards',
        'bar-pulse':   'barPulse 0.9s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: 0, transform: 'translateY(16px)' },
          to:   { opacity: 1, transform: 'translateY(0)' },
        },
        pathDraw: {
          from: { strokeDashoffset: '3000' },
          to:   { strokeDashoffset: '0' },
        },
        barPulse: {
          '0%,100%': { transform: 'scaleY(0.2)' },
          '50%':     { transform: 'scaleY(1)' },
        },
      },
    },
  },
  plugins: [],
}
